image: nqoki709/monolis_build:latest

stages:
  - lib_build
  - test
  - doxy_build
  - deploy

build_gedatsu:
  stage: lib_build
  script:
    - ./install_lib.sh
    - make FLAGS=DEBUG
  artifacts:
    paths:
      - bin
      - test

test_gedatsu:
  stage: test
  script:
    - cd src_test
    - ./run.CI.sh
    - cd ../wrapper_test
    - ./run.sh
  dependencies:
    - build_gedatsu

doxygen_gedatsu:
  stage: doxy_build
  script:
    - cd manual
    - doxygen
  artifacts:
    paths:
      - manual

pages:
  stage: deploy
  dependencies:
    - doxygen_gedatsu
  script:
    - mv manual/html public
  artifacts:
    paths:
      - public
