image: hrektts/doxygen:latest

stages:
  - build
  - deploy

build_doxygen:
  stage: build
  script:
    - cd doc
    - doxygen
  artifacts:
    paths:
      - doc

pages:
  stage: deploy
  dependencies:
    - build_doxygen
  script:
    - mv doc/docs public
  artifacts:
    paths:
      - public
